<?php 
$response = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <ns1:calendarioCircuitosResponse xmlns:ns1="types.circuito.dtp">
         <calendarioCircuitosResponseRow>
            <fecSal>06/06/2015</fecSal>
            <serviciosCircuito>
               <refSer>270412</refSer>
               <ideSer>PRBE011</ideSer>
               <nomSer>PRAGA Y ALEMANIA DEL ESTE TI 8 DÍAS / 7 NOCHES (PROD. SUPERIOR)</nomSer>
               <codCsc>SU</codCsc>
               <codRga>TI</codRga>
               <numNoc>7</numNoc>
               <productosCircuito>
                  <refPro>266363</refPro>
                  <SuplAerIda>6000</SuplAerIda>
                  <SuplAerVue>6000</SuplAerVue>
                  <idePro>OFCCEMA1500</idePro>
                  <idGrup>3</idGrup>
                  <nomLar>PRAGA Y ALEMANIA DEL ESTE 8 DÍAS / 7 NOCHES (PROD. SUPERIOR)</nomLar>
                  <preciosRegimen>
                     <codRga>TI</codRga>
                     <pvp>106000</pvp>
                     <cadRes>rO0ABXNyABh1dGlsaWRhZGVzLkNhZGVuYVJlc2VydmEAAAAAAAAAAQIAKEwABmFnZW5jeXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wABmFw</cadRes>
                     <status>OK</status>
                     <tiposHabitacion>
                        <pvpHab>106000</pvpHab>
                        <codGtr>IND</codGtr>
                        <modDet>SGL</modDet>
                        <dscDet>INDIVIDUAL</dscDet>
                        <codCha>ES</codCha>
                        <dscCha>ESTÁNDAR</dscCha>
                        <paxMin>1</paxMin>
                        <paxMax>1</paxMax>
                        <chlMin>0</chlMin>
                        <chlMax>-1</chlMax>
                        <paxTot>1</paxTot>
                        <paxTotMax>-1</paxTotMax>
                        <itmPrd>3</itmPrd>
                     </tiposHabitacion>
                  </preciosRegimen>
                  <fecUltReg>30/06/2015</fecUltReg>
               </productosCircuito>
            </serviciosCircuito>
            <serviciosCircuito>
               <refSer>270413</refSer>
               <ideSer>PRBE010</ideSer>
               <nomSer>PRAGA Y ALEMANIA DEL ESTE AD 8 DÍAS / 7 NOCHES (PROD. SUPERIOR)</nomSer>
               <codCsc>SU</codCsc>
               <codRga>AD</codRga>
               <numNoc>7</numNoc>
               <productosCircuito>
                  <refPro>266363</refPro>
                  <SuplAerIda>6000</SuplAerIda>
                  <SuplAerVue>6000</SuplAerVue>
                  <idePro>OFCCEMA1500</idePro>
                  <idGrup>3</idGrup>
                  <nomLar>PRAGA Y ALEMANIA DEL ESTE 8 DÍAS / 7 NOCHES (PROD. SUPERIOR)</nomLar>
                  <preciosRegimen>
                     <codRga>AD</codRga>
                     <pvp>84500</pvp>
                     <cadRes>rO0ABXNyABh1dGlsaWRhZGVzLkNhZGVuYVJlc2VydmEAAAAAAAAAAQIAKEwABmFnZW5jeXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wABm</cadRes>
                     <status>OK</status>
                     <tiposHabitacion>
                        <pvpHab>84500</pvpHab>
                        <codGtr>IND</codGtr>
                        <modDet>SGL</modDet>
                        <dscDet>INDIVIDUAL</dscDet>
                        <codCha>ES</codCha>
                        <dscCha>ESTÁNDAR</dscCha>
                        <paxMin>1</paxMin>
                        <paxMax>1</paxMax>
                        <chlMin>0</chlMin>
                        <chlMax>-1</chlMax>
                        <paxTot>1</paxTot>
                        <paxTotMax>-1</paxTotMax>
                        <itmPrd>3</itmPrd>
                     </tiposHabitacion>
                  </preciosRegimen>
                  <fecUltReg>30/06/2015</fecUltReg>
               </productosCircuito>
            </serviciosCircuito>
         </calendarioCircuitosResponseRow>
         <calendarioCircuitosResponseRow>
            <fecSal>20/06/2015</fecSal>
            <serviciosCircuito>
               <refSer>270412</refSer>
               <ideSer>PRBE011</ideSer>
               <nomSer>PRAGA Y ALEMANIA DEL ESTE TI 8 DÍAS / 7 NOCHES (PROD. SUPERIOR)</nomSer>
               <codCsc>SU</codCsc>
               <codRga>TI</codRga>
               <numNoc>7</numNoc>
               <productosCircuito>
                  <refPro>266363</refPro>
                  <SuplAerIda>6000</SuplAerIda>
                  <SuplAerVue>6000</SuplAerVue>
                  <idePro>OFCCEMA1500</idePro>
                  <idGrup>3</idGrup>
                  <nomLar>PRAGA Y ALEMANIA DEL ESTE 8 DÍAS / 7 NOCHES (PROD. SUPERIOR)</nomLar>
                  <preciosRegimen>
                     <codRga>TI</codRga>
                     <pvp>106000</pvp>
                    <cadRes>rO0ABXNyABh1dGlsaWRhZGVzLkNhZGVuYVJlc2VydmEAAAAAAAAAAQIAKEwABmFnZW5jeXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wABmFwdEFycnEAfgABTAAGYXB0RGVwcQB)AAFMAA1jYWRlbmFCbG9xdWVvcQB)AAFMAA9jYWRlbmFWdWVsb3NJZGFxAH4AAUwAD2NhZGVuYVZ1ZWxvc1Z0YXEAgABTAAJY2F0ZWdvcmlhcQB)AAFMAAZjb2RBZ25xAH4AAUwACWNvZGFncnVwYXEAfgABTAAPY29uZWN0aW9uU3RyaW5ncQB)AAFMAAZlZGFOaW5xAH4AAUwABmVkYWRlc3EAfgABTAAJZXN0RGlzU2VydAATTGphdmEvbGFuZy9JbnRlZ2VyO0wACWVzdERpc1RyYXEAfgACTAAGZmVjRmlucQB)AAFMAAZmZWNJbmlxAH4AAUwABmlkR3J1cHEAfgACTAAJaWRVc3VhcmlvcQB)AAFMAAZpZGlvbWFxAH4AAUwABmxvZ2hhbHEAfgABTAAGbnVtQWRscQB)AAJMAAZudW1JbmZxAH4AAkwABm51bU5pbnEAfgACTAAGb2ZmaWNlcQB)AAFMAARwYWlzcQB)AAFMAAZwYXNBZ25xAH4AAUwACXBvYmxhY2lvbnEAfgABTAAJcHJvdmVlZG9ycQB)AAFMAAlwcm92aW5jaWFxAH4AAUwABnB2cFNlcnEAfgACTAAGcHZwVHJhcQB)AAJMAAZyZWZQcm9xAH4AAkwABnJlZlNlcnEAfgACTAAHcmVnaW1lbnEAfgABTAAGc3RyTW9kcQB)AAFMAAZzd2lEaXJ0ABNMamF2YS9sYW5nL0Jvb2xlYW47TAAGc3dpUmVzcQB)AAFMAAZzd2lWdWVxAH4AAUwABnN5c3RlbXEAfgABTAAGdGlwU2VycQB)AAF4cHB0AAVDQ0U3MHQAA01BRHBwcHBwcHB0AAMzMDtwc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAAAAJxAH4ACnQACjI3LzA2LzIwMTV0AAoyMC8wNi8yMDE1c3EAfgAIAAAAA3QACUhBTENPTkNPTXQAA0VTUHBzcQB)AAgAAAABc3EAfgAIAAAAAHEAfgARcHBwcHBwc3EAfgAIAAFvMHNxAH4ACAAALuBzcQB)AAgABBB7c3EAfgAIAAQgTHB0AAkzQDFAMSMwIztzcgARamF2YS5sYW5nLkJvb2xlYW7NIHKA1Zz67gIAAVoABXZhbHVleHABdAABTnBwdAAIQ0lSQ1VJVE8=</cadRes>
                     <status>OK</status>
                     <tiposHabitacion>
                        <pvpHab>106000</pvpHab>
                        <codGtr>IND</codGtr>
                        <modDet>SGL</modDet>
                        <dscDet>INDIVIDUAL</dscDet>
                        <codCha>ES</codCha>
                        <dscCha>ESTÁNDAR</dscCha>
                        <paxMin>1</paxMin>
                        <paxMax>1</paxMax>
                        <chlMin>0</chlMin>
                        <chlMax>-1</chlMax>
                        <paxTot>1</paxTot>
                        <paxTotMax>-1</paxTotMax>
                        <itmPrd>3</itmPrd>
                     </tiposHabitacion>
                  </preciosRegimen>
                  <fecUltReg>30/06/2015</fecUltReg>
               </productosCircuito>
            </serviciosCircuito>
            <serviciosCircuito>
               <refSer>270413</refSer>
               <ideSer>PRBE010</ideSer>
               <nomSer>PRAGA Y ALEMANIA DEL ESTE AD 8 DÍAS / 7 NOCHES (PROD. SUPERIOR)</nomSer>
               <codCsc>SU</codCsc>
               <codRga>AD</codRga>
               <numNoc>7</numNoc>
               <productosCircuito>
                  <refPro>266363</refPro>
                  <SuplAerIda>6000</SuplAerIda>
                  <SuplAerVue>6000</SuplAerVue>
                  <idePro>OFCCEMA1500</idePro>
                  <idGrup>3</idGrup>
                  <nomLar>PRAGA Y ALEMANIA DEL ESTE 8 DÍAS / 7 NOCHES (PROD. SUPERIOR)</nomLar>
                  <preciosRegimen>
                     <codRga>AD</codRga>
                     <pvp>84500</pvp>
                     <cadRes>rO0ABXNyABh1dGlsaWRhZGVzLkNhZGVuYVJlc2VydmEAAAAAAAAAAQIAKEwABmFnZW5jeXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wABmFwdEFycnEAfgABTAAGYXB0RGVwcQB)AAFMAA1jYWRlbmFCbG9xdWVvcQB)AAFMAA9jYWRlbmFWdWVsb3NJZGFxAH4AAUwAD2NhZGVuYVZ1ZWxvc1Z0YXEAfgABTAAJY2F0ZWdvcmlhcQB)AAFMAAZjb2RBZ25xAH4AAUwACWNvZGFncnVwYXEAfgABTAAPY29uZWN0aW9uU3RyaW5ncQB)AAFMAAZlZGFOaW5xAH4AAUwABmVkYWRlc3EAfgABTAAJZXN0RGlzU2VydAATTGphdmEvbGFuZy9JbnRlZ2VyO0wACWVzdERpc1RyYXEAfgACTAAG</cadRes>
                     <status>OK</status>
                     <tiposHabitacion>
                        <pvpHab>84500</pvpHab>
                        <codGtr>IND</codGtr>
                        <modDet>SGL</modDet>
                        <dscDet>INDIVIDUAL</dscDet>
                        <codCha>ES</codCha>
                        <dscCha>ESTÁNDAR</dscCha>
                        <paxMin>1</paxMin>
                        <paxMax>1</paxMax>
                        <chlMin>0</chlMin>
                        <chlMax>-1</chlMax>
                        <paxTot>1</paxTot>
                        <paxTotMax>-1</paxTotMax>
                        <itmPrd>3</itmPrd>
                     </tiposHabitacion>
                  </preciosRegimen>
                  <fecUltReg>30/06/2015</fecUltReg>
               </productosCircuito>
            </serviciosCircuito>
         </calendarioCircuitosResponseRow>
      </ns1:calendarioCircuitosResponse>
   </soapenv:Body>
</soapenv:Envelope>';

?>